name: Pull Upstream

on:
  push: {}
#  schedule:
#    - cron: '0 0 1 * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Create branch
        run: |
          git remote add upstream https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/antora/antora-ui-default.git
          git fetch upstream
          git checkout -b upstream-merge
          git merge --no-ff upstream/master

      - name: Create pull-request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              head:  upstream-merge,
              base:  master,
              title: 'Merge upstream into master',
              body: 'todo',
            });
