name: Pull Upstream

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create branch
        run: |
          git remote add upstream https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/antora/antora-ui-default.git
          git fetch upstream
          git checkout -b upstream-merge
          git merge --no-ff upstream/master
